# Generated by Django 2.0.5 on 2018-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('tasks', '0009_auto_20180507_0328')
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=False,max_length=200)),
                ('firstname', models.CharField(blank=True, max_length=1000)),
                ('lastname', models.CharField(blank=True, max_length=1000)),
                ('phone', models.IntegerField(blank=False, max_length=11)),
                ('password', models.CharField(blank=False, max_length=100)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
